services:
  sz-server:
    build:
      context: ./sz-server
      dockerfile: Dockerfile
    container_name: sz-server
    ports:
      - "5001:3000"
    env_file:
      - .env.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backendai
      - redis
      - postgres
    networks:
      - saleszium-network
    volumes:
      - ./sz-server:/app
      - /app/node_modules

  backendai:
    build:
      context: ./backendai
      dockerfile: Dockerfile
    container_name: backendai
    ports:
      - "5002:5002"
    env_file:
      - .env.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    networks:
      - saleszium-network
    volumes:
      - ./backendai:/app

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - saleszium-network

  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saleszium_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - saleszium-network

networks:
  saleszium-network:
    driver: bridge

volumes:
  postgres_data:
